name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g npm@7 -f
      - run: npm install
      - run: npm run build
        env:
          CI: true
          BLOG_URL: https://blog.s1h.org
          POST_API: /ghost/api/v3/content/posts/
          GHOST_CONTENT_KEY: ${{ secrets.GHOST_CONTENT_KEY }}
          POST_LIMIT: 3
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          ARGS: "-rtgoDzvO --no-links"
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SOURCE: "public/"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
